"""delete token from ding user

Revision ID: 1b0bd0d2ea7f
Revises: 7d8c7b0674bf
Create Date: 2026-02-21 10:38:24.686340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0bd0d2ea7f'
down_revision: Union[str, Sequence[str], None] = '7d8c7b0674bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dingding_user', 'refresh_token_expire_at')
    op.drop_column('dingding_user', 'access_token')
    op.drop_column('dingding_user', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dingding_user', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('dingding_user', sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('dingding_user', sa.Column('refresh_token_expire_at', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
