"""add job_seeker tables

Revision ID: 4eea2dde5299
Revises: 8415cc24fe89
Create Date: 2026-03-01 00:58:28.515144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4eea2dde5299'
down_revision: Union[str, Sequence[str], None] = '8415cc24fe89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_seekers',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', name='jobseekerstatus'), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_seekers'))
    )
    op.create_index(op.f('ix_job_seekers_email'), 'job_seekers', ['email'], unique=True)
    op.create_index(op.f('ix_job_seekers_username'), 'job_seekers', ['username'], unique=True)
    op.create_table('job_seeker_chat_sessions',
    sa.Column('job_seeker_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['job_seekers.id'], name=op.f('fk_job_seeker_chat_sessions_job_seeker_id_job_seekers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_seeker_chat_sessions'))
    )
    op.create_index(op.f('ix_job_seeker_chat_sessions_job_seeker_id'), 'job_seeker_chat_sessions', ['job_seeker_id'], unique=False)
    op.create_table('job_seeker_chat_histories',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_position_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['job_seeker_chat_sessions.id'], name=op.f('fk_job_seeker_chat_histories_session_id_job_seeker_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_seeker_chat_histories'))
    )
    op.create_index(op.f('ix_job_seeker_chat_histories_session_id'), 'job_seeker_chat_histories', ['session_id'], unique=False)
    # 先创建 position_embeddings 表结构，不包含 vector 字段
    op.create_table('position_embeddings',
    sa.Column('position_id', sa.String(length=100), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.Enum('TITLE', 'DESCRIPTION', 'REQUIREMENTS', 'FULL', name='chunktype'), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_position_embeddings_position_id_positions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_embeddings'))
    )
    op.create_index(op.f('ix_position_embeddings_position_id'), 'position_embeddings', ['position_id'], unique=False)
    # 然后添加 vector 字段
    op.add_column('position_embeddings', sa.Column('embedding', pgvector.sqlalchemy.Vector(1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_embeddings_position_id'), table_name='position_embeddings')
    op.drop_table('position_embeddings')
    op.drop_index(op.f('ix_job_seeker_chat_histories_session_id'), table_name='job_seeker_chat_histories')
    op.drop_table('job_seeker_chat_histories')
    op.drop_index(op.f('ix_job_seeker_chat_sessions_job_seeker_id'), table_name='job_seeker_chat_sessions')
    op.drop_table('job_seeker_chat_sessions')
    op.drop_index(op.f('ix_job_seekers_username'), table_name='job_seekers')
    op.drop_index(op.f('ix_job_seekers_email'), table_name='job_seekers')
    op.drop_table('job_seekers')
    # ### end Alembic commands ###
