"""interview enum add padding

Revision ID: 8415cc24fe89
Revises: 1b0bd0d2ea7f
Create Date: 2026-02-24 17:36:32.245427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8415cc24fe89'
down_revision: Union[str, Sequence[str], None] = '1b0bd0d2ea7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
